name: CI-test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag pratap/docker-react

      - name: Run Test
        run: docker run pratap/docker-react npm run test
